apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - onepassword.yaml

patches:

  - target:
      kind: Deployment
      name: altinn-ebevis-service
    path: deployment.yaml
