apiVersion: v1
kind: Service
metadata:
  name: altinn-ebevis-service
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
spec:
  selector:
    app: altinn-ebevis-service
  type: LoadBalancer
  ports:
    - {name: '8080', port: 8080}
